// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CocheraTp.Models;

public partial class LUGARE
{
    public string id_lugar { get; set; }

    public bool? seccion_uno { get; set; }

    public bool? seccion_dos { get; set; }

    public int? id_tipo_vehiculo { get; set; }

    [JsonIgnore]
    public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURAs { get; set; } = new List<DETALLE_FACTURA>();
    [JsonIgnore]
    public virtual ICollection<REMITO> REMITOs { get; set; } = new List<REMITO>();
    [JsonIgnore]
    public virtual TIPOS_VEHICULO id_tipo_vehiculoNavigation { get; set; }
}